### ISSUE TITLE
API documentation link is broken

### ISSUE THREAD

**Issue by lboue** [adafruit/Adafruit_CircuitPython_DS248x#3]
API documentation link is broken:

 API documentation for this library can be found on Read the Docs: https://docs.circuitpython.org/projects/ds248x/en/latest/

https://github.com/adafruit/Adafruit_CircuitPython_DS248x/blob/1d76d6e82b67b38dede59470fe32de5dab2840fb/README.rst?plain=1#L115

Could you fix it?

Regards

**Comment by BlitzCityDIY** [comment]
hihi- thanks for pointing that out. it is fixed now.
